env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
    - avoidEscape: true
  semi:
    - error
    - never
  "@typescript-eslint/no-empty-interface": off
  "@typescript-eslint/no-empty-function": off
