name: Deploy to GitHub Pages

on:
  push:
    branches: [ ci-build ] # FixMe: テスト用ブランチ: mainに修正する
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # shellで $cd $GITHUB_WORKSPACE を行いmerge→github.tokenを用いてpushすればdevmasx/merge-branch@v1.3.1を使用せずに書けると思われる
      - uses: actions/checkout@v2
      - name: Deploy
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: ci-build # ここでfrom_branchを指定するならactions/checkout@v2要らないのでは？？ # FixMe: テスト用ブランチ: mainに修正する
          target_branch: gh-pages-test # FixMe: テスト用ブランチ: gh-pagesに修正する
          github_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          ref: gh-pages-test
      - run: yarn install
      - run: yarn build
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          commit_message: yarn build
          branch: gh-pages-test
